### ISSUE TITLE
Base64 url in css/genericons/genericons.css

### ISSUE THREAD

**Issue by mandrag0ra** [ThemeZee/leeway#1]
Hi,

It's not really an issue, I just would like to understand.

As I use the theme on a wordpress site, I found a base64 url for [genericons.css](https://github.com/ThemeZee/leeway/blob/5985a6a496a02364f4d5a92b8101791e92ba18d3/css/genericons/genericons.css#L22).
I do understand that it comes from [genericons](http://genericons.com) but can't just decode the string.
Maybe did you ?

**Comment by Netzberufler** [comment]
Hi there,

Please see the comment above the code:
/* IE8 and below use EOT and allow cross-site embedding. 
   IE9 uses WOFF which is base64 encoded to allow cross-site embedding.
   So unfortunately, IE9 will throw a console error, but it'll still work.
   When the font is base64 encoded, cross-site embedding works in Firefox */

And I did not create the file, the theme just embeds the Genericons icon font so I have never decoded that.

Cheers,
Thomas

**Comment by mandrag0ra** [comment]
Thanks for your answer @Netzberufler.
